name: al_hadith
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.0+6
environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  go_router: ^14.2.0
  gap: ^3.0.1
  dio: ^5.8.0+1
  archive: ^4.0.5
  drift: ^2.33.0
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_animate: ^4.5.2
  google_fonts: ^8.0.2
  scrollable_positioned_list: ^0.3.8
  share_plus: ^10.1.4
  wakelock_plus: ^1.5.2
  url_launcher: ^6.3.1
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  firebase_database: ^12.4.1
  google_sign_in: ^6.2.2
  flutter_svg: ^2.3.0
  package_info_plus: ^9.0.1
  dartx: ^1.2.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: ^3.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/img/

  fonts:
    - family: Indopak Nastaleeq
      fonts:
        - asset: assets/fonts/Indopak Nastaleeq font.ttf
    - family: Me Quran
      fonts:
        - asset: assets/fonts/me_quran_volt_newmet.ttf
    - family: QPC Hafs
      fonts:
        - asset: assets/fonts/QPC Hafs font.ttf


icons_launcher:
  image_path: "assets/img/logo.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#11263B"
      adaptive_foreground_image: "assets/img/logo.png"
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
      image_path: "assets/img/logo.png"

    windows:
      enable: false
      image_path: "assets/img/logo.png"

    linux:
      enable: true
      image_path: "assets/img/logo.png"

